// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBQPk6WC2I0UA71q1jjpTLf4gCxh-rDkgU',
    appId: '1:704721335840:web:548bb1a06787d7cce5ee45',
    messagingSenderId: '704721335840',
    projectId: 'flash-chat-1a4b5',
    authDomain: 'flash-chat-1a4b5.firebaseapp.com',
    storageBucket: 'flash-chat-1a4b5.appspot.com',
    measurementId: 'G-CDBJF66M33',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyCk4ScuCMPyZaXxaSmFvuZP6eEr-xdwbog',
    appId: '1:704721335840:android:0888ab6f75cbcc88e5ee45',
    messagingSenderId: '704721335840',
    projectId: 'flash-chat-1a4b5',
    storageBucket: 'flash-chat-1a4b5.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyC3egUt-ydATmslwWNG_lryHixFM2Eg_FM',
    appId: '1:704721335840:ios:2f37bd7ae546ceeee5ee45',
    messagingSenderId: '704721335840',
    projectId: 'flash-chat-1a4b5',
    storageBucket: 'flash-chat-1a4b5.appspot.com',
    iosBundleId: 'com.example.flashChat',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyC3egUt-ydATmslwWNG_lryHixFM2Eg_FM',
    appId: '1:704721335840:ios:f54a7083cf987180e5ee45',
    messagingSenderId: '704721335840',
    projectId: 'flash-chat-1a4b5',
    storageBucket: 'flash-chat-1a4b5.appspot.com',
    iosBundleId: 'com.example.flashChat.RunnerTests',
  );
}
